# Nordic theme for Helix
# From : https://github.com/AlexvZyl/nordic.nvim
# Author : Owen Friedman <5-pebble@protonmail.com>
# License: MIT License

# Syntax Highlighting
"attribute" = { fg = "white0" }
"type" = { fg = "yellow_base" }
"type.enum.variant" = { fg = "cyan_bright" }
"constructor" = { fg = "cyan_bright" }
"constant" = { fg = "magenta_bright" }
"constant.character" = { fg = "green_base" }
"constant.character.escape" = { fg = "magenta_bright" }
"string" = { fg = "green_base" }
"string.regex" = { fg = "magenta_bright" }
"comment" = { fg = "gray4", modifiers = ["italic"] }
"variable" = { fg = "white0" }
"variable.builtin" = { fg = "blue0" }
"variable.other.member" = { fg = "cyan_bright" }
"label" = { fg = "orange_base", modifiers = ["bold"] }
"punctuation.delimiter" = { fg = "gray5", modifiers = ["italic"] }
"punctuation.special" = { fg = "orange_base" }
"keyword" = { fg = "orange_base", modifiers = ["bold"] }
"operator" = { fg = "white0" }
"function" = { fg = "blue2" }
"function.macro" = { fg = "red_bright" }
"tag" = { fg = "blue1" }
"namespace" = { fg = "yellow_dim" }
"special" = { fg = "yellow_base", modifiers = [
  "bold",
] } # fuzzy highlight (picker)

# Markup
"markup.heading.1" = { fg = "yellow_base", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange_base", modifiers = ["bold"] }
"markup.heading.3" = { fg = "magenta_base", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green_base" }
"markup.heading.5" = { fg = "blue2", modifiers = ["italic"] }
"markup.heading.6" = { fg = "cyan_base", modifiers = ["italic"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.list" = { fg = "yellow_base", modifiers = ["bold"] }
"markup.link" = { fg = "blue1", "underline.style" = "line" }
"markup.quote" = { fg = "gray4", modifiers = ["italic"] }
"markup.raw.inline" = { fg = "gray4" }
"markup.raw.block" = { fg = "green_base" }

# Diffs
"diff.plus" = { fg = "green_base" }
"diff.minus" = { fg = "red_base" }
"diff.delta" = { fg = "blue1" }

# UI
"ui.background" = { fg = "white0", bg = "black2" }
"ui.cursor" = { fg = "black1", bg = "gray4" }
"ui.cursor.primary" = { fg = "black1", bg = "white0" }
"ui.cursor.match" = { modifiers = ["bold"] }
"ui.linenr" = { fg = "gray2" }
"ui.linenr.selected" = { fg = "gray4" }
"ui.statusline" = { fg = "white0", bg = "black0" }
"ui.statusline.inactive" = { fg = "gray4", bg = "black0" }
"ui.popup" = { bg = "black1" }
"ui.window" = { fg = "gray4" }
"ui.help" = { bg = "black1" }
"ui.text.focus" = { bg = "gray2" }
"ui.virtual.ruler" = { bg = "gray1" }
"ui.virtual.jump-label" = { bg = "black0", modifiers = ["reversed", "bold"] }
"ui.menu" = { bg = "black1" }
"ui.menu.selected" = { bg = "gray4" }
"ui.menu.scroll" = { fg = "gray4", bg = "gray0" }
"ui.selection" = { bg = "gray2" }
"ui.cursorline.primary" = { bg = "gray1" }

# Diagnostic Messages
"error" = { fg = "red_base" }
"warning" = { fg = "yellow_base" }
"info" = { fg = "blue1" }
"hint" = { fg = "green_base" }
"diagnostic.error" = { underline = { color = "red_base", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow_base", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue1", style = "curl" } }
"diagnostic.hint" = { underline = { color = "green_base", style = "curl" } }


# Color Palette
[palette]
# Black
black0 = "#191D24"
black1 = "#1E222A"
black2 = "#222630"

# Gray
gray0 = "#242933"
# Polar night
gray1 = "#2E3440"
gray2 = "#3B4252"
gray3 = "#434C5E"
gray4 = "#4C566A"
# a light blue/gray
# from @nightfox.nvim
gray5 = "#60728A"

# White
# reduce_blue variant
white0 = "#C0C8D8"
# Snow storm
white1 = "#D8DEE9"
white2 = "#E5E9F0"
white3 = "#ECEFF4"

# Blue
# Frost
blue0 = "#5E81AC"
blue1 = "#81A1C1"
blue2 = "#88C0D0"

# Cyan:
cyan_base = "#8FBCBB"
cyan_bright = "#9FC6C5"
cyan_dim = "#80B3B2"

# Aurora (from Nord theme)
# Red
red_base = "#BF616A"
red_bright = "#C5727A"
red_dim = "#B74E58"

# Orange
orange_base = "#D08770"
orange_bright = "#D79784"
orange_dim = "#CB775D"

# Yellow
yellow_base = "#EBCB8B"
yellow_bright = "#EFD49F"
yellow_dim = "#E7C173"

# Green
green_base = "#A3BE8C"
green_bright = "#B1C89D"
green_dim = "#97B67C"

# Magenta
magenta_base = "#B48EAD"
magenta_bright = "#BE9DB8"
magenta_dim = "#A97EA1"
