return {
    -- Groups from LSP semantic tokens
    LspClass = { link = '@class' },
    LspComment = { link = '@comment' },
    LspEnum = { link = '@type' },
    LspEnumMember = { link = '@type.builtin' },
    LspEvent = { link = '@label' },
    LspFunction = { link = '@function' },
    LspInterface = { link = '@type' },
    LspKeyword = { link = '@keyword' },
    LspMacro = { link = '@macro' },
    LspMethod = { link = '@method' },
    LspModifier = { link = '@operator' },
    LspNamespace = { link = '@namespace' },
    LspNumber = { link = '@number' },
    LspOperator = { link = '@operator' },
    LspParameter = { link = '@parameter' },
    LspProperty = { link = '@property' },
    LspRegexp = { link = '@string.regex' },
    LspString = { link = '@text' },
    LspStruct = { link = '@type' },
    LspType = { link = '@type' },
    LspTypeParameter = { link = '@type' },
    LspVariable = { link = '@variable' },
}
